### PR TITLE
Update entries.coffee

### PR DESCRIPTION
**Pull request by gni**
Fix Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.

### CODE REVIEW

**Comment by varemenos** [comment]
Do you mind if I keep this open for a couple of weeks? I'm currently in the army and will return home in the 8th is August so I will be able to merge and release a new version of the toolbar that follows the new API and fixes this issue properly

**Comment by gni** [comment]
@varemenos There is no problem.
Good luck.

**Comment by dead-claudia** [comment]
@varemenos @4p The icon disappears with this patch...just a word of caution.

**Comment by varemenos** [comment]
That's why I didn't merge it right away, I need to test and make sure everything works. Hope you guys don't mind the delay.

**Comment by gni** [comment]
@isiahmeadows Hmm.. I only test this on Debian & Ubuntu. Which operating system are you using ?

**Comment by gni** [comment]
Oh my bad. I see now. I start to use icon: 'minus-square-o'
I close the request & wait for an update from @varemenos

**Pull request closed without merging**
