### PR TITLE
Editor functionality

### PR DESCRIPTION
**Pull request by Drumkruk**
Hi,

I like editor functionality in the toolbar. Please consider this functionality. 

Tim

added auto-indent item
added fold-all item
added unfold-all item

### CODE REVIEW

**Comment by varemenos** [comment]
Nice, thanks for contributing Tim

**Comment by Drumkruk** [comment]
No problem! Shouldn't we update the description now as well? I didn't do it in my pull request because I didn't thought you would directly merge and release it.

**Comment by varemenos** [comment]
Yes that's correct but I've neglected it a couple more times in the past due to high workload so later this week I will update the description and screenshot to reflect the latest version.

**Comment by Drumkruk** [comment]
Alright! Good luck!

**Pull request merged**
